Web/Controllers/UserController.cs
using Services.Managers.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace Web.Controllers
{
    [Route("[controller]/[action]")]
    public class UserController : BaseController
    {
        private readonly ILogger<UserController> _logger;
        private readonly ISessionManager _sessionManager;

        public UserController(ILoggerFactory loggerFactory, ISessionManager sessionManager)
        {
            _logger = loggerFactory.CreateLogger<UserController>();
            _sessionManager = sessionManager;
        }

        [HttpPost]
        public async Task<IActionResult> GetUserByUserId()
        {
            try
            {
                var sessionUser = await _sessionManager.GetUser();
                return new JsonResult(sessionUser);
            }
            catch (System.Exception e)
            {
                _logger.LogError(e, e.Message);
                return Json(0);
            }
        }
    }
}

Web/Pages/Admin/Permissions/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Models.ServiceModels.Admin.Permissions;
using Services.Admin.Contracts;

namespace Web.Pages
{
    public class CreatePermissionModel : BasePageModel
    {
        #region Private Fields

        private readonly IPermissionsService _permissionsService;

        #endregion

        #region Properties

        [BindProperty]
        public CreatePermissionRequest FormData { get; set; }

        #endregion

        #region Constructors

        public CreatePermissionModel(IPermissionsService permissionsService)
        {
            _permissionsService = permissionsService;
            FormData = new CreatePermissionRequest();
        }

        #endregion

        public async Task OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var response = await _permissionsService.CreatePermission(FormData);
                if (response.IsSuccessful)
                {
                    AddNotifications(response);
                    return RedirectToPage("/Admin/Permissions/Index");
                }
                AddFormErrors(response);
            }
            return Page();
        }
    }
}

Web/Pages/Admin/Permissions/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Models.ServiceModels.Admin.Permissions;
using Services.Admin.Contracts;

namespace Web.Pages
{
    public class EditPermissionModel : BasePageModel
    {
        #region Private Fields

        private readonly IPermissionsService _permissionsService;

        #endregion

        #region Properties

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty]
        public UpdatePermissionRequest FormData { get; set; }

        public string? Key { get; set; }

        #endregion

        #region Constructors

        public EditPermissionModel(IPermissionsService permissionsService)
        {
            _permissionsService = permissionsService;
            FormData = new UpdatePermissionRequest();
        }

        #endregion

        public async Task<IActionResult> OnGet()
        {
            var response = await _permissionsService.GetPermission(new GetPermissionRequest()
            {
                Id = Id
            });

            if (!response.IsSuccessful)
            {
                return NotFound();
            }

            Key = response.Permission.Key;
            FormData = new UpdatePermissionRequest()
            {
                Id = response.Permission.Id,
                Description = response.Permission.Description,
                GroupName = response.Permission.Group_Name,
                Name = response.Permission.Name
            };

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                FormData.Id = Id;
                var response = await _permissionsService.UpdatePermission(FormData);
                if (response.IsSuccessful)
                {
                    AddNotifications(response);
                    return RedirectToPage("/Admin/Permissions/Index");
                }
                AddFormErrors(response);
            }
            return Page();
        }
    }
}

Web/Pages/Admin/Roles/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Models.DomainModels;
using Models.ServiceModels.Admin.Roles;
using Services.Admin.Contracts;
using Services.Managers.Contracts;

namespace Web.Pages
{
    public class CreateRoleModel : BasePageModel
    {
        #region Private Fields

        private readonly IRoleService _roleService;
        private readonly ICacheManager _cache;

        #endregion

        #region Properties

        [BindProperty]
        public CreateRoleRequest FormData { get; set; }

        public List<PermissionEntity> PermissionsLookup { get; set; }

        #endregion

        #region Constructors

        public CreateRoleModel(IRoleService roleService, ICacheManager cache)
        {
            _roleService = roleService;
            _cache = cache;
            PermissionsLookup = new List<PermissionEntity>();
            FormData = new CreateRoleRequest();
        }

        #endregion

        public async Task OnGet()
        {
            PermissionsLookup = await _cache.Permissions();
            FormData = new CreateRoleRequest();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var response = await _roleService.CreateRole(FormData);
                if (response.IsSuccessful)
                {
                    AddNotifications(response);
                    return RedirectToPage("/Admin/Roles/Index");
                }
                AddFormErrors(response);
            }
            return Page();
        }
    }
}

Web/Pages/Admin/Roles/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Models.ServiceModels.Admin.Roles;
using Models.DomainModels;
using System.Collections.Generic;
using System.Linq;
using Services.Managers.Contracts;
using Services.Admin.Contracts;
using Models;

namespace Web.Pages
{
    public class EditRoleModel : BasePageModel
    {
        #region Private Fields

        private readonly IRoleService _roleService;
        private readonly ICacheManager _cache;

        #endregion

        #region Properties

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty]
        public UpdateRoleRequest FormData { get; set; }

        public RoleEntity? RoleEntity { get; set; }

        public List<PermissionEntity> PermissionsLookup { get; set; }

        #endregion

        #region Constructors

        public EditRoleModel(IRoleService roleService, ICacheManager cache)
        {
            _roleService = roleService;
            _cache = cache;
            PermissionsLookup = new List<PermissionEntity>();
            FormData = new UpdateRoleRequest();
        }

        #endregion

        public async Task<IActionResult> OnGet()
        {
            var response = await _roleService.GetRole(new GetRoleRequest()
            {
                Id = Id
            });

            if (!response.IsSuccessful)
            {
                return NotFound();
            }

            PermissionsLookup = await _cache.Permissions();
            RoleEntity = response.Role;
            FormData = new UpdateRoleRequest()
            {
                Id = response.Role.Id,
                Description = response.Role.Description,
                Name = response.Role.Name,
                PermissionIds = response.Permissions.Select(c => new CheckboxItemSelection() {
                    Id = c.Id,
                    Selected = true
                }).ToList()
            };

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                if (FormData != null)
                {
                    FormData.Id = Id;
                }
                var response = await _roleService.UpdateRole(FormData);
                if (response.IsSuccessful)
                {
                    AddNotifications(response);
                    return RedirectToPage("/Admin/Roles/Index");
                }
                AddFormErrors(response);
            }
            var roleResponse = await _roleService.GetRole(new GetRoleRequest()
            {
                Id = Id
            });
            PermissionsLookup = await _cache.Permissions();
            RoleEntity = roleResponse.Role;
            return Page();
        }

        public async Task<IActionResult> OnPostDisableRole(int id)
        {
            var response = await _roleService.DisableRole(new DisableRoleRequest()
            {
                Id = id
            });
            AddNotifications(response);
            return RedirectToPage("/Admin/Roles/Index");
        }

        public async Task<IActionResult> OnPostEnableRole(int id)
        {
            var response = await _roleService.EnableRole(new EnableRoleRequest()
            {
                Id = id
            });
            AddNotifications(response);
            return RedirectToPage("/Admin/Roles/Index");
        }
    }
}

Web/Pages/Admin/SessionEvents/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Models.ServiceModels.Admin.SessionEvents;
using Services.Admin.Contracts;

namespace Web.Pages
{
    public class CreateSessionEventModel : BasePageModel
    {
        #region Private Fields

        private readonly ISessionService _sessionService;

        #endregion

        #region Properties

        [BindProperty]
        public CreateSessionEventRequest FormData { get; set; }

        #endregion

        #region Constructors

        public CreateSessionEventModel(ISessionService sessionService)
        {
            _sessionService = sessionService;
            FormData = new CreateSessionEventRequest();
        }

        #endregion

        public async Task OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var response = await _sessionService.CreateSessionEvent(FormData);
                if (response.IsSuccessful)
                {
                    AddNotifications(response);
                    return RedirectToPage("/Admin/SessionEvents/Index");
                }
                AddFormErrors(response);
            }
            return Page();
        }
    }
}

Web/Pages/Admin/Users/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Models.DomainModels;
using Models.ServiceModels.Admin.Users;
using Services.Admin.Contracts;
using Services.Managers.Contracts;

namespace Web.Pages
{
    public class EditUserModel : BasePageModel
    {
        #region Private Fields

        private readonly IUserService _userService;
        private readonly ICacheManager _cache;

        #endregion

        #region Properties

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty]
        public UpdateUserRequest FormData { get; set; }

        public UserEntity? UserEntity { get; set; }

        public List<RoleEntity> RolesLookup { get; set; }

        #endregion

        #region Constructors

        public EditUserModel(IUserService userService, ICacheManager cache)
        {
            _userService = userService;
            _cache = cache;
            RolesLookup = new List<RoleEntity>();
            FormData = new UpdateUserRequest();
        }

        #endregion

        public async Task<IActionResult> OnGet()
        {
            var response = await _userService.GetUser(new GetUserRequest()
            {
                Id = Id
            });

            if (!response.IsSuccessful)
            {
                return NotFound();
            }

            RolesLookup = await _cache.Roles();
            UserEntity = response.User;
            FormData = new UpdateUserRequest()
            {
                Username = response.User.Username,
                EmailAddress = response.User.Email_Address,
                FirstName = response.User.First_Name,
                LastName = response.User.Last_Name,
                MobileNumber = response.User.Mobile_Number,
                RoleIds = response.Roles.Select(r => r.Id).ToList()
            };
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                if (FormData != null)
                {
                    FormData.Id = Id;
                }
                var response = await _userService.UpdateUser(FormData);
                if (response.IsSuccessful)
                {
                    AddNotifications(response);
                    return RedirectToPage("/Admin/Users/Index");
                }
                AddFormErrors(response);
            }
            var userResponse = await _userService.GetUser(new GetUserRequest()
            {
                Id = Id
            });
            RolesLookup = await _cache.Roles();
            UserEntity = userResponse.User;
            return Page();
        }

        public async Task<IActionResult> OnPostDisableUser(int id)
        {
            var response = await _userService.DisableUser(new Models.ServiceModels.Admin.Users.DisableUserRequest()
            {
                Id = id
            });
            AddNotifications(response);
            return RedirectToPage("/Admin/Users/Index");
        }

        public async Task<IActionResult> OnPostEnableUser(int id)
        {
            var response = await _userService.EnableUser(new Models.ServiceModels.Admin.Users.EnableUserRequest()
            {
                Id = id
            });
            AddNotifications(response);
            return RedirectToPage("/Admin/Users/Index");
        }

        public async Task<IActionResult> OnPostUnlockUser(int id)
        {
            var response = await _userService.UnlockUser(new Models.ServiceModels.Admin.Users.UnlockUserRequest()
            {
                Id = id
            });
            AddNotifications(response);
            return RedirectToPage("/Admin/Users/Index");
        }

        public async Task<IActionResult> OnPostConfirmRegistration(int id)
        {
            var response = await _userService.ConfirmRegistration(new Models.ServiceModels.Admin.Users.ConfirmRegistrationRequest()
            {
                Id = id
            });
            AddNotifications(response);
            return RedirectToPage("/Admin/Users/Index");
        }

        public async Task<IActionResult> OnPostGenerateResetPasswordUrl([FromBody] GenerateResetPasswordUrlRequest request)
        {
            ModelState.Clear(); // needed to prevent other forms being included in validation
            if (TryValidateModel(request))
            {
                var response = await _userService.GenerateResetPasswordUrl(request);
                if (response.IsSuccessful)
                {
                    return new JsonResult(response);
                }
                AddFormErrors(response);
                return new UnprocessableEntityObjectResult(ModelState);
            }
            return new BadRequestObjectResult(ModelState);
        }

        public async Task<IActionResult> OnPostSendResetPasswordEmail([FromBody] SendResetPasswordEmailRequest request)
        {
            ModelState.Clear(); // needed to prevent other forms being included in validation
            if (TryValidateModel(request))
            {
                var response = await _userService.SendResetPasswordEmail(request);
                if (response.IsSuccessful)
                {
                    return new JsonResult(response);
                }
                AddFormErrors(response);
                return new UnprocessableEntityObjectResult(ModelState);
            }
            return new BadRequestObjectResult(ModelState);
        }
    }
}

Web/Pages/Admin/Users/Index1.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web.Pages.Admin.Users
{
    public class Index1Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web/Pages/Admin/Users/Create.cshtml
@page
@model CreateUserModel
@{
    ViewData.SetMeta("Create User");
}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">@ViewData["Title"]</h1>

    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card border-0 shadow-lg">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="px-5 py-4">
                        <form asp-controller="Admin" asp-action="CreateUser" method="post" class="form-horizontal" role="form">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="FormData.Username" class="control-label"></label>
                                <input asp-for="FormData.Username" class="form-control" />
                                <span asp-validation-for="FormData.Username" class="text-danger"></span>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label asp-for="FormData.EmailAddress" class="control-label"></label>
                                    <input asp-for="FormData.EmailAddress" class="form-control" />
                                    <span asp-validation-for="FormData.EmailAddress" class="text-danger"></span>
                                </div>
                                <div class="form-group col-md-6">
                                    <label asp-for="FormData.MobileNumber" class="control-label"></label>
                                    <input asp-for="FormData.MobileNumber" class="form-control" />
                                    <span asp-validation-for="FormData.MobileNumber" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label asp-for="FormData.FirstName" class="control-label"></label>
                                    <input asp-for="FormData.FirstName" class="form-control" />
                                    <span asp-validation-for="FormData.FirstName" class="text-danger"></span>
                                </div>
                                <div class="form-group col-md-6">
                                    <label asp-for="FormData.LastName" class="control-label"></label>
                                    <input asp-for="FormData.LastName" class="form-control" />
                                    <span asp-validation-for="FormData.LastName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label asp-for="FormData.Password" class="control-label"></label>
                                    <input asp-for="FormData.Password" class="form-control" />
                                    <span asp-validation-for="FormData.Password" class="text-danger"></span>
                                </div>
                                <div class="form-group col-md-6">
                                    <label asp-for="FormData.PasswordConfirm" class="control-label"></label>
                                    <input asp-for="FormData.PasswordConfirm" class="form-control" />
                                    <span asp-validation-for="FormData.PasswordConfirm" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label asp-for="FormData.RoleIds" class="control-label"></label>
                                    <multiselect asp-for="FormData.RoleIds" asp-items="Model.RolesLookup.ToSelectList()"></multiselect>
                                </div>
                            </div>
                            <div class="form-group my-4">
                                <button type="submit" class="btn btn-primary btn-block">Create</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->

Web/Pages/Admin/Users/Index.cshtml
@page
@model ManageUsersModel
@{
    ViewData.SetMeta("Manage Users");
}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">@ViewData["Title"] </h1>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <a asp-page="/Admin/Users/Create" class="btn btn-primary">Create</a>

            <a id="btnReloadData" href="#" class="btn btn-primary float-right">
                <span class="icon text-white">
                    <i class="fas fa-sync"></i>
                </span>
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="dataTable" class="table table-striped" style="width: 100%;" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Username</th>
                            <th>Email Address</th>
                            <th>First Name</th>
                            <th>Registered Date</th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@* disable modal *@
<div class="modal fade" id="modalDisableUser" tabindex="-1" role="dialog" aria-labelledby="modalDisableUserLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white" id="modalDisableUserLabel">Disable User</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to disable this user?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">No</button>
                <form asp-page-handler="DisableUser" method="post">
                    <input name="Id" type="hidden" />
                    <button type="submit" class="btn btn-primary">Yes</button>
                </form>
            </div>
        </div>
    </div>
</div>

@* enable modal *@
<div class="modal fade" id="modalEnableUser" tabindex="-1" role="dialog" aria-labelledby="modalEnableUserLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white" id="modalEnableUserLabel">Enable User</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to enable this user?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">No</button>
                <form asp-page-handler="EnableUser" method="post">
                    <input name="Id" type="hidden" />
                    <button type="submit" class="btn btn-primary">Yes</button>
                </form>
            </div>
        </div>
    </div>
</div>

@* unlock modal *@
<div class="modal fade" id="modalUnlockUser" tabindex="-1" role="dialog" aria-labelledby="modalUnlockUserLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white" id="modalUnlockUserLabel">Unlock User</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to unlock this user?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">No</button>
                <form asp-page-handler="UnlockUser" method="post">
                    <input name="Id" type="hidden" />
                    <button type="submit" class="btn btn-primary">Yes</button>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts  {

    <script type="text/javascript">

        $(document).ready(function () {

            var table = loadDataTable('@Url.Page("/Admin/Users/Index", "Data")');

            $("#btnReloadData").click(function () {
                table.ajax.reload();
            });

            function loadDataTable(url, params) {

                if (table) {
                    table.destroy();
                }

                table = $('#dataTable').DataTable({
                    ajax: {
                        url: url,
                        data: params,
                        dataSrc: "users",
                    },
                    columns: [
                        {
                            data: "id"
                        },
                        {
                            data: "username"
                        },
                        {
                            data: "email_Address"
                        },
                        {
                            data: "first_Name"
                        },
                        {
                            data: "created_Date",
                            render: {
                                display: function (data) {
                                    return moment(data).format('Do MMMM YYYY');
                                },
                                sort: function (data) {
                                    return moment(data).unix();
                                },
                                filter: function (data) {
                                    return moment(data).format('Do MMMM YYYY');
                                }
                            }
                        },
                        {
                            render: function (data, type, row, meta) {
                                var actionButtons = '';

                                if (row.is_Locked_Out) {
                                    // unlock
                                    actionButtons += '<a href="#" data-toggle="modal" data-target="#modalUnlockUser" data-target-id="' + row.id + '" class="mr-4 text-decoration-none">';
                                    actionButtons += '<i class="fas fa-unlock text-warning" data-toggle="tooltip" data-placement="left" title="Unlock"></i>';
                                    actionButtons += '</a>';
                                }

                                if (row.is_Enabled) {
                                    //disable
                                    actionButtons += '<a href="#" data-toggle="modal" data-target="#modalDisableUser" data-target-id="' + row.id + '" class="mr-4 text-decoration-none">';
                                    actionButtons += '<i class="fas fa-door-closed text-danger" data-toggle="tooltip" data-placement="left" title="Disable"></i>';
                                    actionButtons += '</a>';
                                } else {
                                    // enable
                                    actionButtons += '<a href="#" data-toggle="modal" data-target="#modalEnableUser" data-target-id="' + row.id + '" class="mr-4 text-decoration-none">';
                                    actionButtons += '<i class="fas fa-door-open text-success" data-toggle="tooltip" data-placement="left" title="Enable"></i>';
                                    actionButtons += '</a>';
                                }

                                // edit
                                actionButtons += '<a href="/Admin/Users/Edit?id=' + row.id + '" class="text-decoration-none">';
                                actionButtons += '<i class="fas fa-edit" data-toggle="tooltip" data-placement="left" title="Edit"></i>';
                                actionButtons += '</a>';

                                return actionButtons;
                            }
                        }
                    ],
                    columnDefs: [
                        { targets: -1, orderable: false, className: 'table-actions' }
                    ],
                    order: [
                        [0, 'desc'],
                    ],
                    processing: true,
                    language: {
                        processing: '<div class="spinner-border text-primary" role="status"></div>'
                    },
                    drawCallback: function (settings) {
                        resetToolTips();
                    },
                    createdRow: function(row, data, dataIndex ) {
                        if (data.is_Enabled === false) {
                            $(row).addClass('disabled-row');
                        }
                    }
                });

                return table;

            }

        });

    </script>

}

Web/Pages/Admin/Users/Index1.cshtml
@page
@model Web.Pages.Admin.Users.Index1Model
@{
}