Web/Pages/Admin/Permissions/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Models.ServiceModels.Admin.Permissions;
using Services.Admin.Contracts;

namespace Web.Pages
{
    public class CreatePermissionModel : BasePageModel
    {
        #region Private Fields

        private readonly IPermissionsService _permissionsService;

        #endregion

        #region Properties

        [BindProperty]
        public CreatePermissionRequest FormData { get; set; }

        #endregion

        #region Constructors

        public CreatePermissionModel(IPermissionsService permissionsService)
        {
            _permissionsService = permissionsService;
            FormData = new CreatePermissionRequest();
        }

        #endregion

        public async Task OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var response = await _permissionsService.CreatePermission(FormData);
                if (response.IsSuccessful)
                {
                    AddNotifications(response);
                    return RedirectToPage("/Admin/Permissions/Index");
                }
                AddFormErrors(response);
            }
            return Page();
        }
    }
}

Web/Pages/Admin/Permissions/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Models.ServiceModels.Admin.Permissions;
using Services.Admin.Contracts;

namespace Web.Pages
{
    public class EditPermissionModel : BasePageModel
    {
        #region Private Fields

        private readonly IPermissionsService _permissionsService;

        #endregion

        #region Properties

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty]
        public UpdatePermissionRequest FormData { get; set; }

        public string? Key { get; set; }

        #endregion

        #region Constructors

        public EditPermissionModel(IPermissionsService permissionsService)
        {
            _permissionsService = permissionsService;
            FormData = new UpdatePermissionRequest();
        }

        #endregion

        public async Task<IActionResult> OnGet()
        {
            var response = await _permissionsService.GetPermission(new GetPermissionRequest()
            {
                Id = Id
            });

            if (!response.IsSuccessful)
            {
                return NotFound();
            }

            Key = response.Permission.Key;
            FormData = new UpdatePermissionRequest()
            {
                Id = response.Permission.Id,
                Description = response.Permission.Description,
                GroupName = response.Permission.Group_Name,
                Name = response.Permission.Name
            };

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                FormData.Id = Id;
                var response = await _permissionsService.UpdatePermission(FormData);
                if (response.IsSuccessful)
                {
                    AddNotifications(response);
                    return RedirectToPage("/Admin/Permissions/Index");
                }
                AddFormErrors(response);
            }
            return Page();
        }
    }
}

Web/Pages/Admin/Roles/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Models.DomainModels;
using Models.ServiceModels.Admin.Roles;
using Services.Admin.Contracts;
using Services.Managers.Contracts;

namespace Web.Pages
{
    public class CreateRoleModel : BasePageModel
    {
        #region Private Fields

        private readonly IRoleService _roleService;
        private readonly ICacheManager _cache;

        #endregion

        #region Properties

        [BindProperty]
        public CreateRoleRequest FormData { get; set; }

        public List<PermissionEntity> PermissionsLookup { get; set; }

        #endregion

        #region Constructors

        public CreateRoleModel(IRoleService roleService, ICacheManager cache)
        {
            _roleService = roleService;
            _cache = cache;
            PermissionsLookup = new List<PermissionEntity>();
            FormData = new CreateRoleRequest();
        }

        #endregion

        public async Task OnGet()
        {
            PermissionsLookup = await _cache.Permissions();
            FormData = new CreateRoleRequest();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var response = await _roleService.CreateRole(FormData);
                if (response.IsSuccessful)
                {
                    AddNotifications(response);
                    return RedirectToPage("/Admin/Roles/Index");
                }
                AddFormErrors(response);
            }
            return Page();
        }
    }
}

Web/Pages/Admin/Roles/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Models.ServiceModels.Admin.Roles;
using Models.DomainModels;
using System.Collections.Generic;
using System.Linq;
using Services.Managers.Contracts;
using Services.Admin.Contracts;
using Models;

namespace Web.Pages
{
    public class EditRoleModel : BasePageModel
    {
        #region Private Fields

        private readonly IRoleService _roleService;
        private readonly ICacheManager _cache;

        #endregion

        #region Properties

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty]
        public UpdateRoleRequest FormData { get; set; }

        public RoleEntity? RoleEntity { get; set; }

        public List<PermissionEntity> PermissionsLookup { get; set; }

        #endregion

        #region Constructors

        public EditRoleModel(IRoleService roleService, ICacheManager cache)
        {
            _roleService = roleService;
            _cache = cache;
            PermissionsLookup = new List<PermissionEntity>();
            FormData = new UpdateRoleRequest();
        }

        #endregion

        public async Task<IActionResult> OnGet()
        {
            var response = await _roleService.GetRole(new GetRoleRequest()
            {
                Id = Id
            });

            if (!response.IsSuccessful)
            {
                return NotFound();
            }

            PermissionsLookup = await _cache.Permissions();
            RoleEntity = response.Role;
            FormData = new UpdateRoleRequest()
            {
                Id = response.Role.Id,
                Description = response.Role.Description,
                Name = response.Role.Name,
                PermissionIds = response.Permissions.Select(c => new CheckboxItemSelection() {
                    Id = c.Id,
                    Selected = true
                }).ToList()
            };

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                if (FormData != null)
                {
                    FormData.Id = Id;
                }
                var response = await _roleService.UpdateRole(FormData);
                if (response.IsSuccessful)
                {
                    AddNotifications(response);
                    return RedirectToPage("/Admin/Roles/Index");
                }
                AddFormErrors(response);
            }
            var roleResponse = await _roleService.GetRole(new GetRoleRequest()
            {
                Id = Id
            });
            PermissionsLookup = await _cache.Permissions();
            RoleEntity = roleResponse.Role;
            return Page();
        }

        public async Task<IActionResult> OnPostDisableRole(int id)
        {
            var response = await _roleService.DisableRole(new DisableRoleRequest()
            {
                Id = id
            });
            AddNotifications(response);
            return RedirectToPage("/Admin/Roles/Index");
        }

        public async Task<IActionResult> OnPostEnableRole(int id)
        {
            var response = await _roleService.EnableRole(new EnableRoleRequest()
            {
                Id = id
            });
            AddNotifications(response);
            return RedirectToPage("/Admin/Roles/Index");
        }
    }
}

Web/Pages/Admin/Roles/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Services.Admin.Contracts;

namespace Web.Pages
{
    public class ManageRolesModel : BasePageModel
    {
        #region Private Fields

        private readonly IRoleService _roleService;

        #endregion

        #region Properties


        #endregion

        #region Constructors

        public ManageRolesModel(IRoleService roleService)
        {
            _roleService = roleService;
        }

        #endregion

        public async Task OnGet()
        {
        }

        public async Task<JsonResult> OnGetData()
        {
            var response = await _roleService.GetRoles();
            return new JsonResult(response);
        }

        public async Task<IActionResult> OnPostDisableRole(int id)
        {
            var response = await _roleService.DisableRole(new Models.ServiceModels.Admin.Roles.DisableRoleRequest()
            {
                Id = id
            });
            AddNotifications(response);
            return RedirectToPage("/Admin/Roles/Index");
        }

        public async Task<IActionResult> OnPostEnableRole(int id)
        {
            var response = await _roleService.EnableRole(new Models.ServiceModels.Admin.Roles.EnableRoleRequest()
            {
                Id = id
            });
            AddNotifications(response);
            return RedirectToPage("/Admin/Roles/Index");
        }
    }
}

Web/Pages/Admin/SessionEvents/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Models.ServiceModels.Admin.SessionEvents;
using Services.Admin.Contracts;

namespace Web.Pages
{
    public class CreateSessionEventModel : BasePageModel
    {
        #region Private Fields

        private readonly ISessionService _sessionService;

        #endregion

        #region Properties

        [BindProperty]
        public CreateSessionEventRequest FormData { get; set; }

        #endregion

        #region Constructors

        public CreateSessionEventModel(ISessionService sessionService)
        {
            _sessionService = sessionService;
            FormData = new CreateSessionEventRequest();
        }

        #endregion

        public async Task OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var response = await _sessionService.CreateSessionEvent(FormData);
                if (response.IsSuccessful)
                {
                    AddNotifications(response);
                    return RedirectToPage("/Admin/SessionEvents/Index");
                }
                AddFormErrors(response);
            }
            return Page();
        }
    }
}

Web/Pages/Admin/SessionEvents/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Models.ServiceModels.Admin.SessionEvents;
using Services.Admin.Contracts;

namespace Web.Pages
{
    public class EditSessionEventModel : BasePageModel
    {
        #region Private Fields

        private readonly ISessionService _sessionService;

        #endregion

        #region Properties

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty]
        public UpdateSessionEventRequest FormData { get; set; }

        public string? Key { get; set; }

        #endregion

        #region Constructors

        public EditSessionEventModel(ISessionService sessionService)
        {
            _sessionService = sessionService;
            FormData = new UpdateSessionEventRequest();
        }

        #endregion

        public async Task<IActionResult> OnGet()
        {
            var response = await _sessionService.GetSessionEvent(new GetSessionEventRequest()
            {
                Id = Id
            });

            if (!response.IsSuccessful)
            {
                return NotFound();
            }

            Key = response.SessionEvent.Key;
            FormData = new UpdateSessionEventRequest()
            {
                Id = response.SessionEvent.Id,
                Description = response.SessionEvent.Description
            };

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                FormData.Id = Id;
                var response = await _sessionService.UpdateSessionEvent(FormData);
                if (response.IsSuccessful)
                {
                    AddNotifications(response);
                    return RedirectToPage("/Admin/SessionEvents/Index");
                }
                AddFormErrors(response);
            }
            return Page();
        }
    }
}

Web/Pages/Admin/Users/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Models.DomainModels;
using Models.ServiceModels.Admin.Users;
using Services.Admin.Contracts;
using Services.Managers.Contracts;

namespace Web.Pages
{
    public class CreateUserModel : BasePageModel
    {
        #region Private Fields

        private readonly IUserService _userService;
        private readonly ICacheManager _cache;

        #endregion

        #region Properties

        [BindProperty]
        public CreateUserRequest FormData { get; set; }
        public List<RoleEntity> RolesLookup { get; set; }

        #endregion

        #region Constructors

        public CreateUserModel(IUserService userService, ICacheManager cache)
        {
            _userService = userService;
            _cache = cache;
            RolesLookup = new List<RoleEntity>();
            FormData = new CreateUserRequest();
        }

        #endregion

        public async Task OnGet()
        {
            RolesLookup = await _cache.Roles();
            FormData = new CreateUserRequest();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var response = await _userService.CreateUser(FormData);
                if (response.IsSuccessful)
                {
                    AddNotifications(response);
                    return RedirectToPage("/Admin/Users/Index");
                }
                AddFormErrors(response);
            }
            RolesLookup = await _cache.Roles();
            return Page();
        }
    }
}

Web/Pages/Admin/Roles/Create.cshtml
@page
@model CreateRoleModel
@{
    ViewData.SetMeta("Create Role");
}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">@ViewData["Title"]</h1>

    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card border-0 shadow-lg">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="px-5 py-4">
                        <form asp-controller="Admin" asp-action="CreateRole" method="post" class="form-horizontal" role="form">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="FormData.Name" class="control-label"></label>
                                <input asp-for="FormData.Name" class="form-control" />
                                <span asp-validation-for="FormData.Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="FormData.Description" class="control-label"></label>
                                <input asp-for="FormData.Description" class="form-control" />
                                <span asp-validation-for="FormData.Description" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="FormData.PermissionIds" class="control-label w-100"></label>
                                <multicheckbox asp-for="FormData.PermissionIds" asp-items="Model.PermissionsLookup.ToCheckboxList()"></multicheckbox>
                            </div>
                            <div class="form-group my-4">
                                <button type="submit" class="btn btn-primary btn-block">Create</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>


</div>
<!-- /.container-fluid -->

Web/Pages/Admin/Roles/Edit.cshtml
@page
@model EditRoleModel
@{
    ViewData.SetMeta("Edit Role");
}

@if (Model.RoleEntity != null)
{
    <div class="container-fluid">

        <h1 class="h3 mb-4 text-gray-800">@ViewData["Title"]</h1>

        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card border-0 shadow-lg">
                    <div class="card-header py-3 text-right">
                        @if (Model.RoleEntity.Is_Enabled)
                        {
                            <a href="#" class="btn btn-danger btn-icon-split" data-toggle="modal" data-target="#modalDisableRole" data-target-id="@Model.RoleEntity.Id">
                                <span class="icon text-white-50">
                                    <i class="fas fa-door-closed"></i>
                                </span>
                                <span class="text">Disable</span>
                            </a>
                        }
                        else
                        {
                            <a href="#" class="btn btn-success btn-icon-split" data-toggle="modal" data-target="#modalEnableRole" data-target-id="@Model.RoleEntity.Id">
                                <span class="icon text-white-50">
                                    <i class="fas fa-door-open"></i>
                                </span>
                                <span class="text">Enable</span>
                            </a>
                        }
                    </div>
                    <div class="card-body p-0">
                        <div class="px-5 py-4">
                            <form asp-controller="Admin" asp-action="EditRole" method="post" class="form-horizontal" role="form">
                                <div asp-validation-summary="All" class="text-danger"></div>
                                <div class="form-group">
                                    <label asp-for="FormData.Name" class="control-label"></label>
                                    <input asp-for="FormData.Name" class="form-control" />
                                    <span asp-validation-for="FormData.Name" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="FormData.Description" class="control-label"></label>
                                    <input asp-for="FormData.Description" class="form-control" />
                                    <span asp-validation-for="FormData.Description" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="FormData.PermissionIds" class="control-label w-100"></label>
                                    <multicheckbox asp-for="FormData.PermissionIds" asp-items="Model.PermissionsLookup.ToCheckboxList()"></multicheckbox>
                                </div>
                                <div class="form-group my-4">
                                    <button type="submit" class="btn btn-primary btn-block">Update</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@* disable modal *@
<div class="modal fade" id="modalDisableRole" tabindex="-1" role="dialog" aria-labelledby="modalDisableRoleLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white" id="modalDisableRoleLabel">Disable Role</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to disable this role?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">No</button>
                <form asp-page-handler="DisableRole" method="post">
                    <input name="Id" type="hidden" />
                    <button type="submit" class="btn btn-primary">Yes</button>
                </form>
            </div>
        </div>
    </div>
</div>

@* enable modal *@
<div class="modal fade" id="modalEnableRole" tabindex="-1" role="dialog" aria-labelledby="modalEnableRoleLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white" id="modalEnableRoleLabel">Enable Role</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to enable this role?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">No</button>
                <form asp-page-handler="EnableRole" method="post">
                    <input name="Id" type="hidden" />
                    <button type="submit" class="btn btn-primary">Yes</button>
                </form>
            </div>
        </div>
    </div>
</div>

Web/Pages/Admin/Roles/Index.cshtml
@page
@model ManageRolesModel
@{
    ViewData.SetMeta("Manage Role");
}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">@ViewData["Title"] </h1>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <a asp-page="/Admin/Roles/Create" class="btn btn-primary">Create</a>

            <a id="btnReloadData" href="#" class="btn btn-primary float-right">
                <span class="icon text-white">
                    <i class="fas fa-sync"></i>
                </span>
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="dataTable" class="table table-striped" style="width: 100%;" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Created Date</th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@* disable modal *@
<div class="modal fade" id="modalDisableRole" tabindex="-1" role="dialog" aria-labelledby="modalDisableRoleLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white" id="modalDisableRoleLabel">Disable Role</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to disable this role?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">No</button>
                <form asp-page-handler="DisableRole" method="post">
                    <input name="Id" type="hidden" />
                    <button type="submit" class="btn btn-primary">Yes</button>
                </form>
            </div>
        </div>
    </div>
</div>

@* enable modal *@
<div class="modal fade" id="modalEnableRole" tabindex="-1" role="dialog" aria-labelledby="modalEnableRoleLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white" id="modalEnableRoleLabel">Enable Role</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to enable this role?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">No</button>
                <form asp-page-handler="EnableRole" method="post">
                    <input name="Id" type="hidden" />
                    <button type="submit" class="btn btn-primary">Yes</button>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts  {

    <script type="text/javascript">

        $(document).ready(function () {

        var table = loadDataTable('@Url.Page("/Admin/Roles/Index", "Data")');

        $("#btnReloadData").click(function () {
                table.ajax.reload();
        });

         function loadDataTable(url, params) {

                if (table) {
                    table.destroy();
                }

                table = $('#dataTable').DataTable({
                    ajax: {
                        url: url,
                        data: params,
                        dataSrc: "roles",
                    },
                    columns: [
                        {
                            data: "name"
                        },
                        {
                            data: "description"
                        },
                        {
                            data: "created_Date",
                            render: {
                                display: function (data) {
                                    return moment(data).format('Do MMMM YYYY');
                                },
                                sort: function (data) {
                                    return moment(data).unix();
                                },
                                filter: function (data) {
                                    return moment(data).format('Do MMMM YYYY');
                                }
                            }
                        },
                        {
                            render: function (data, type, row, meta) {
                                var actionButtons = '';

                                if (row.is_Enabled) {
                                    //disable
                                    actionButtons += '<a href="#" data-toggle="modal" data-target="#modalDisableRole" data-target-id="' + row.id + '" class="mr-4 text-decoration-none">';
                                    actionButtons += '<i class="fas fa-door-closed text-danger" data-toggle="tooltip" data-placement="left" title="Disable"></i>';
                                    actionButtons += '</a>';
                                } else {
                                    // enable
                                    actionButtons += '<a href="#" data-toggle="modal" data-target="#modalEnableRole" data-target-id="' + row.id + '" class="mr-4 text-decoration-none">';
                                    actionButtons += '<i class="fas fa-door-open text-success" data-toggle="tooltip" data-placement="left" title="Enable"></i>';
                                    actionButtons += '</a>';
                                }

                                // edit
                                actionButtons += '<a href="/Admin/Roles/Edit?id=' + row.id + '" class="text-decoration-none" >';
                                actionButtons += '<i class="fas fa-edit" data-toggle="tooltip" data-placement="left" title="Edit"></i>';
                                actionButtons += '</a>';

                                return actionButtons;
                            }
                        }
                    ],
                    columnDefs: [
                        { targets: -1, orderable: false, className: 'table-actions' }
                    ],
                    order: [
                        [0, 'desc'],
                    ],
                    processing: true,
                    language: {
                        processing: '<div class="spinner-border text-primary" role="status"></div>'
                    },
                    drawCallback: function (settings) {
                        resetToolTips();
                    },
                    createdRow: function(row, data, dataIndex ) {
                        if (data.is_Enabled === false) {
                            $(row).addClass('disabled-row');
                        }
                    }
                });

                return table;

            }


        });

    </script>

}